name: caf_face_authenticator
description: CAF Face Authenticator SDK
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cs_liveness_flutter:
    git:
      url: https://github.com/ClearSale/LivenessPluginFlutter.git
      ref: 1.1.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: 0.3.0
  mock_web_server: 5.0.0-nullsafety.1

flutter: